# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class HotScrapyItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    id = scrapy.Field()
    source = scrapy.Field()
    brand = scrapy.Field()
    type = scrapy.Field()
    link = scrapy.Field()
    year = scrapy.Field()
    price = scrapy.Field()
    seller = scrapy.Field()
    kind = scrapy.Field()
    sys = scrapy.Field()
    color = scrapy.Field()
    locate = scrapy.Field()
    miles = scrapy.Field()
    cc = scrapy.Field()
    power = scrapy.Field()
    car_gas = scrapy.Field()
    safe_bag = scrapy.Field()
    abs = scrapy.Field()
    air_con = scrapy.Field()
    back_radar = scrapy.Field()
    back_screen = scrapy.Field()
    gps = scrapy.Field()
    window = scrapy.Field()
    auto_windows = scrapy.Field()
    auto_side = scrapy.Field()
    l_chair = scrapy.Field()
    alert = scrapy.Field()
    auto_chair = scrapy.Field()
    cd = scrapy.Field()
    media = scrapy.Field()
    ss = scrapy.Field()
    alu = scrapy.Field()
    hid = scrapy.Field()
    tpms = scrapy.Field()
    fog_lights = scrapy.Field()
    ldws = scrapy.Field()
    blind_spot = scrapy.Field()
    electric_tailgate = scrapy.Field()
    silde_door = scrapy.Field()
    whole_window = scrapy.Field()
    key_less = scrapy.Field()
    isofix = scrapy.Field()
    lcd = scrapy.Field()
    shift_paddles = scrapy.Field()
    es = scrapy.Field()
    led = scrapy.Field()
    trc = scrapy.Field()
    tcs = scrapy.Field()
    ldws = scrapy.Field()
    aeb = scrapy.Field()
    acc = scrapy.Field()
    hud = scrapy.Field()
    multi_wheel = scrapy.Field()
    auto_park = scrapy.Field()
    people = scrapy.Field()
    female_used = scrapy.Field()
    turbo = scrapy.Field()
    warranty = scrapy.Field()
    epb = scrapy.Field()
    clc = scrapy.Field()
